import type { MedicineStockItem } from "./dummy-data";

/**
 * Data Resmi Ketersediaan Perbekalan Farmasi UPTD Instalasi Farmasi Kab. Kotabaru
 * Periode: Juni 2026
 * Sumber:
 * - 40 Item Survei Obat Indikator (Obat Generik Esensial)
 * - 60 Item Laporan Ketersediaan Obat Program Prioritas (TB, Gizi, Malaria, HIV, dll)
 * - 75 Item Perbekalan Pendukung (Obat Emergensi, Vaksin & Serum, BMHP)
 */
export const realMedicineStock: MedicineStockItem[] = [
  {
    "id": "stk-ind-001",
    "code": "IND-001",
    "name": "Alopurinol tab 100 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 164000,
    "status": "AVAILABLE",
    "avgUsage": 14116.0,
    "mos": 11.62,
    "expiryDate": null,
    "nomenklatur": "Antipirai",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-002",
    "code": "IND-002",
    "name": "Amlodipin tab 10 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 200000,
    "status": "AVAILABLE",
    "avgUsage": 35760.0,
    "mos": 5.59,
    "expiryDate": null,
    "nomenklatur": "Antihipertensi Sistemik \u2013 Calcium Channel Blocker (CCB)",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-003",
    "code": "IND-003",
    "name": "Kaptopril tab 25 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 8400,
    "status": "LOW",
    "avgUsage": 8958.0,
    "mos": 0.94,
    "expiryDate": null,
    "nomenklatur": "Antihipertensi Sistemik \u2013 ACE Inhibitor",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-004",
    "code": "IND-004",
    "name": "Spironolakton tab 25 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 6000,
    "status": "AVAILABLE",
    "avgUsage": 200.0,
    "mos": 30.0,
    "expiryDate": null,
    "nomenklatur": "Diuretik",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-005",
    "code": "IND-005",
    "name": "Antasida, kombinasi aluminium hidroksida 200 mg, magnesium hidroksida 200 mg; tablet kunyah",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 28100,
    "status": "LOW",
    "avgUsage": 25060.0,
    "mos": 1.12,
    "expiryDate": null,
    "nomenklatur": "Antasida",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-006",
    "code": "IND-006",
    "name": "Omeprazol kaps 20 mg",
    "category": "Obat Generik",
    "unit": "Kapsul",
    "quantity": 41800,
    "status": "LOW",
    "avgUsage": 15018.0,
    "mos": 2.78,
    "expiryDate": null,
    "nomenklatur": "Antiulkus \u2013 Agonis Reseptor H2/PPI",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-007",
    "code": "IND-007",
    "name": "Amoksisilin tab 500 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 385600,
    "status": "AVAILABLE",
    "avgUsage": 27808.0,
    "mos": 13.87,
    "expiryDate": null,
    "nomenklatur": "Antibakteri Sistemik",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-008",
    "code": "IND-008",
    "name": "Klorfeniramin tab 4 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 121200,
    "status": "AVAILABLE",
    "avgUsage": 8266.0,
    "mos": 14.66,
    "expiryDate": null,
    "nomenklatur": "Antialergi dan Obat untuk Anafilaksis",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-009",
    "code": "IND-009",
    "name": "Domperidon tab 10 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 24700,
    "status": "AVAILABLE",
    "avgUsage": 5750.0,
    "mos": 4.3,
    "expiryDate": null,
    "nomenklatur": "Antiemetik",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-010",
    "code": "IND-010",
    "name": "Ketokonazol krim 2%",
    "category": "Obat Generik",
    "unit": "Tube",
    "quantity": 1665,
    "status": "AVAILABLE",
    "avgUsage": 262.0,
    "mos": 6.35,
    "expiryDate": null,
    "nomenklatur": "Antifungi Topikal",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-011",
    "code": "IND-011",
    "name": "Asam askorbat (vitamin C) tab 50 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 149000,
    "status": "AVAILABLE",
    "avgUsage": 13444.0,
    "mos": 11.08,
    "expiryDate": null,
    "nomenklatur": "Vitamin Lainnya dan Mineral",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-012",
    "code": "IND-012",
    "name": "Glimepirid tab 2 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 46600,
    "status": "AVAILABLE",
    "avgUsage": 7366.0,
    "mos": 6.33,
    "expiryDate": null,
    "nomenklatur": "Antidiabetes \u2013 Insulin secretagogue (Sulfonilurea)",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-013",
    "code": "IND-013",
    "name": "Metformin tab 500 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 336800,
    "status": "AVAILABLE",
    "avgUsage": 24872.0,
    "mos": 13.54,
    "expiryDate": null,
    "nomenklatur": "Antidiabetes \u2013 Non insulin secretagogue (Biguanid, inhibitor alpha glucosidase)",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-014",
    "code": "IND-014",
    "name": "Parasetamol tab 500 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 608300,
    "status": "AVAILABLE",
    "avgUsage": 53925.0,
    "mos": 11.28,
    "expiryDate": null,
    "nomenklatur": "Analgesik Non Narkotik \u2013 Antipiretik",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-015",
    "code": "IND-015",
    "name": "Natrium diklofenak tab sal enterik 50 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 253300,
    "status": "AVAILABLE",
    "avgUsage": 15300.0,
    "mos": 16.56,
    "expiryDate": null,
    "nomenklatur": "Analgesik Non Narkotik - Antiinflamasi Non Steroid",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-016",
    "code": "IND-016",
    "name": "Betametason krim 0,1%",
    "category": "Obat Generik",
    "unit": "Tube",
    "quantity": 4800,
    "status": "AVAILABLE",
    "avgUsage": 554.0,
    "mos": 8.66,
    "expiryDate": null,
    "nomenklatur": "Antiinflamasi dan antipruritik topikal",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-017",
    "code": "IND-017",
    "name": "Metilprednisolon tab 4 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 163000,
    "status": "AVAILABLE",
    "avgUsage": 20050.0,
    "mos": 8.13,
    "expiryDate": null,
    "nomenklatur": "Kortikosteroid",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-018",
    "code": "IND-018",
    "name": "Salbutamol tab 2 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 62500,
    "status": "AVAILABLE",
    "avgUsage": 4372.0,
    "mos": 14.3,
    "expiryDate": null,
    "nomenklatur": "Antiasma",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-019",
    "code": "IND-019",
    "name": "Epinefrin (Adrenalin) Inj 1 mg/mL",
    "category": "Obat Generik",
    "unit": "Ampul",
    "quantity": 440,
    "status": "LOW",
    "avgUsage": 26.0,
    "mos": 16.92,
    "expiryDate": null,
    "nomenklatur": "Obat untuk Syok Kardiogenik dan Sepsis",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-020",
    "code": "IND-020",
    "name": "Lidokain inj 2%",
    "category": "Obat Generik",
    "unit": "Ampul",
    "quantity": 2100,
    "status": "AVAILABLE",
    "avgUsage": 171.0,
    "mos": 12.28,
    "expiryDate": null,
    "nomenklatur": "Anastetik Lokal",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-021",
    "code": "IND-021",
    "name": "Asiklovir tab 200 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 1000.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Antiherpes",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-022",
    "code": "IND-022",
    "name": "Simvastatin tab 10 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 219700,
    "status": "AVAILABLE",
    "avgUsage": 20325.0,
    "mos": 10.81,
    "expiryDate": null,
    "nomenklatur": "Antihiperlipidemia",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-023",
    "code": "IND-023",
    "name": "Permetrin krim 5%",
    "category": "Obat Generik",
    "unit": "Tube",
    "quantity": 2991,
    "status": "AVAILABLE",
    "avgUsage": 100.0,
    "mos": 29.91,
    "expiryDate": null,
    "nomenklatur": "Antiskabies",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-024",
    "code": "IND-024",
    "name": "Hidrogen Peroksida lar 3%",
    "category": "Obat Generik",
    "unit": "Botol",
    "quantity": 125,
    "status": "LOW",
    "avgUsage": 1.0,
    "mos": 125.0,
    "expiryDate": null,
    "nomenklatur": "Antiseptik",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-025",
    "code": "IND-025",
    "name": "Isosorbid dinitrat tab 5 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 1100,
    "status": "AVAILABLE",
    "avgUsage": 300.0,
    "mos": 3.67,
    "expiryDate": null,
    "nomenklatur": "Antiangina",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-026",
    "code": "IND-026",
    "name": "Ketokonazol tab 200 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 25750,
    "status": "AVAILABLE",
    "avgUsage": 533.0,
    "mos": 48.31,
    "expiryDate": null,
    "nomenklatur": "Antifungi Sistemik",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-027",
    "code": "IND-027",
    "name": "n-Asetilsistein kaps 200 mg",
    "category": "Obat Generik",
    "unit": "Kapsul",
    "quantity": 100000,
    "status": "AVAILABLE",
    "avgUsage": 8350.0,
    "mos": 11.98,
    "expiryDate": null,
    "nomenklatur": "Obat Batuk",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-028",
    "code": "IND-028",
    "name": "OAT KDT Kategori 1: 4 KDT/FDC mengandung: rifampisin 150 mg, isoniazid 75 mg, pirazinamid 400 mg, etambutol 275 mg 2 KDT/FDC mengandung: rifampisin 150 mg, isoniazid 75 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 219,
    "status": "LOW",
    "avgUsage": 91.0,
    "mos": 2.41,
    "expiryDate": null,
    "nomenklatur": "Obat Tuberkulosis",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-029",
    "code": "IND-029",
    "name": "Primakuin tab 15 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 6470,
    "status": "AVAILABLE",
    "avgUsage": 233.0,
    "mos": 27.77,
    "expiryDate": null,
    "nomenklatur": "Obat Malaria",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-030",
    "code": "IND-030",
    "name": "Kombinasi KDT/FDC mengandung: tenofovir disoproksil fumarat 300 mg, lamivudin 300 mg, efavirenz 600 mg; tab",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 450,
    "status": "LOW",
    "avgUsage": 45.0,
    "mos": 10.0,
    "expiryDate": null,
    "nomenklatur": "Obat HIV/AIDS",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-031",
    "code": "IND-031",
    "name": "Kombinasi KDT/FDC mengandung Fe; asam folat; tab sal",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 287000,
    "status": "AVAILABLE",
    "avgUsage": 29542.0,
    "mos": 9.71,
    "expiryDate": null,
    "nomenklatur": "Gizi Ibu Hamil dan Rheumatri",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-032",
    "code": "IND-032",
    "name": "Retinol (Vitamin A) Kapsul Lunak 200.000 IU",
    "category": "Obat Generik",
    "unit": "Kapsul",
    "quantity": 16000,
    "status": "LOW",
    "avgUsage": 13654.0,
    "mos": 1.17,
    "expiryDate": null,
    "nomenklatur": "Gizi Balita",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-033",
    "code": "IND-033",
    "name": "Fitomenadion (vitamin K1) inj 2 mg/mL (i.m.)",
    "category": "Obat Generik",
    "unit": "Ampul",
    "quantity": 4630,
    "status": "AVAILABLE",
    "avgUsage": 193.0,
    "mos": 23.99,
    "expiryDate": null,
    "nomenklatur": "Obat yang Memengaruhi Koagulasi",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-034",
    "code": "IND-034",
    "name": "Metilergometerin Injeksi 0,2 mg/mL",
    "category": "Obat Generik",
    "unit": "Ampul",
    "quantity": 365,
    "status": "LOW",
    "avgUsage": 109.0,
    "mos": 3.35,
    "expiryDate": null,
    "nomenklatur": "Oksitoksik",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-035",
    "code": "IND-035",
    "name": "Albendazol susp 400 mg/10 mL",
    "category": "Obat Generik",
    "unit": "Botol",
    "quantity": 3256,
    "status": "AVAILABLE",
    "avgUsage": 9.0,
    "mos": 361.78,
    "expiryDate": null,
    "nomenklatur": "Antelmintik",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-036",
    "code": "IND-036",
    "name": "Zinc Tablet Dispersible 20 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 46700,
    "status": "AVAILABLE",
    "avgUsage": 4842.0,
    "mos": 9.64,
    "expiryDate": null,
    "nomenklatur": "Obat untuk Diare",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-037",
    "code": "IND-037",
    "name": "Kloramfenikol Salep Mata 1%",
    "category": "Obat Generik",
    "unit": "Tube",
    "quantity": 2648,
    "status": "AVAILABLE",
    "avgUsage": 89.0,
    "mos": 29.75,
    "expiryDate": null,
    "nomenklatur": "Antimikroba untuk Mata",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-038",
    "code": "IND-038",
    "name": "Trifluoperazin tab sal selaput 5 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 3400,
    "status": "AVAILABLE",
    "avgUsage": 67.0,
    "mos": 50.75,
    "expiryDate": null,
    "nomenklatur": "Antipsikotik",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-039",
    "code": "IND-039",
    "name": "Diazepam tab 5 mg",
    "category": "Obat Generik",
    "unit": "Tablet",
    "quantity": 1400,
    "status": "AVAILABLE",
    "avgUsage": 67.0,
    "mos": 20.9,
    "expiryDate": null,
    "nomenklatur": "Antiansietas",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-ind-040",
    "code": "IND-040",
    "name": "Magnesium sulfat inj 40% (i.v.)",
    "category": "Obat Generik",
    "unit": "Ampul",
    "quantity": 386,
    "status": "LOW",
    "avgUsage": 31.0,
    "mos": 12.45,
    "expiryDate": null,
    "nomenklatur": "Antiepilepsi-Antikonvulsi",
    "source": "INDIKATOR",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-001",
    "code": "PRG-001",
    "name": "Garam Oralit Serbuk",
    "category": "Obat Program",
    "unit": "Sachet",
    "quantity": 12200,
    "status": "AVAILABLE",
    "avgUsage": 1591.67,
    "mos": 7.66,
    "expiryDate": "2027-05-30",
    "nomenklatur": "Diare & Rehidrasi",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-002",
    "code": "PRG-002",
    "name": "Zinc Tablet Dispersible 20 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 46700,
    "status": "AVAILABLE",
    "avgUsage": 4841.67,
    "mos": 9.65,
    "expiryDate": "2027-05-30",
    "nomenklatur": "Diare & Rehidrasi",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-003",
    "code": "PRG-003",
    "name": "Albendazol susp 400 mg/10 ml",
    "category": "Obat Program",
    "unit": "Botol",
    "quantity": 3256,
    "status": "AVAILABLE",
    "avgUsage": 8.75,
    "mos": 372.11,
    "expiryDate": "2027-11-30",
    "nomenklatur": "Filariasis & Cacingan",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-004",
    "code": "PRG-004",
    "name": "Albendazol tab 400 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 117100,
    "status": "AVAILABLE",
    "avgUsage": 10833.33,
    "mos": 10.81,
    "expiryDate": "2027-06-30",
    "nomenklatur": "Filariasis & Cacingan",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-005",
    "code": "PRG-005",
    "name": "DEC tab 100 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Filariasis & Cacingan",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-006",
    "code": "PRG-006",
    "name": "Azitromisiin tab 500 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 1480,
    "status": "AVAILABLE",
    "avgUsage": 90.0,
    "mos": 16.44,
    "expiryDate": "2027-05-30",
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-007",
    "code": "PRG-007",
    "name": "Anti Anemi - Kombinasi KDT/FDC mengandung:  a. Fe sulfat/Fe fumarat/Fe glukonat (setara dengan 60 mg Fe elemental)  b. asam folat 0,4 mg Tablet Salut",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 287000,
    "status": "AVAILABLE",
    "avgUsage": 29541.67,
    "mos": 9.72,
    "expiryDate": "2027-12-30",
    "nomenklatur": "Gizi & Mikronutrien",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-008",
    "code": "PRG-008",
    "name": "Formula-100",
    "category": "Obat Program",
    "unit": "Sachet",
    "quantity": 600,
    "status": "LOW",
    "avgUsage": 460.33,
    "mos": 1.3,
    "expiryDate": "2027-02-28",
    "nomenklatur": "Gizi & Mikronutrien",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-009",
    "code": "PRG-009",
    "name": "Formula-75",
    "category": "Obat Program",
    "unit": "Sachet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Gizi & Mikronutrien",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-010",
    "code": "PRG-010",
    "name": "Mineral Mix",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Gizi & Mikronutrien",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-011",
    "code": "PRG-011",
    "name": "Ready To Use Therapeutic Food (RUTF)",
    "category": "Obat Program",
    "unit": "Sachet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Gizi & Mikronutrien",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-012",
    "code": "PRG-012",
    "name": "Retinol (Vitamin A) 100.000 IU",
    "category": "Obat Program",
    "unit": "Kapsul",
    "quantity": 100,
    "status": "LOW",
    "avgUsage": 524.5,
    "mos": 0.19,
    "expiryDate": "2027-04-30",
    "nomenklatur": "Gizi & Mikronutrien",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-013",
    "code": "PRG-013",
    "name": "Retinol (Vitamin A) 200.000 IU",
    "category": "Obat Program",
    "unit": "Kapsul",
    "quantity": 16000,
    "status": "LOW",
    "avgUsage": 13654.17,
    "mos": 1.17,
    "expiryDate": "2026-11-30",
    "nomenklatur": "Gizi & Mikronutrien",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-014",
    "code": "PRG-014",
    "name": "Daklatavir 30 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Hepatitis C",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-015",
    "code": "PRG-015",
    "name": "Daklatavir 60 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 28.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Hepatitis C",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-016",
    "code": "PRG-016",
    "name": "Elbasvir 50 mg +  Grazoprevir 100 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Hepatitis C",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-017",
    "code": "PRG-017",
    "name": "KDT Sofosbuvir 400 mg + Daclatasvir 60 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 1148,
    "status": "AVAILABLE",
    "avgUsage": 0.0,
    "mos": null,
    "expiryDate": "2028-06-30",
    "nomenklatur": "Hepatitis C",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-018",
    "code": "PRG-018",
    "name": "Sofosbufir tab 400 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-019",
    "code": "PRG-019",
    "name": "Tenofovir 300 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 8700,
    "status": "AVAILABLE",
    "avgUsage": 350.0,
    "mos": 24.86,
    "expiryDate": "2027-04-30",
    "nomenklatur": "HIV / AIDS",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-020",
    "code": "PRG-020",
    "name": "Kombinasi KDT/FDC mengandung: Tenofovir Disoproksil Fumarat 300 mg; Lamivudin 300 mg; Dolutegravir 50 mg.",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 4080,
    "status": "LOW",
    "avgUsage": 1600.0,
    "mos": 2.55,
    "expiryDate": "2027-09-30",
    "nomenklatur": "HIV / AIDS",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-021",
    "code": "PRG-021",
    "name": "Kombinasi KDT/FDC mengandung: Tenofovir Disoproksil Fumarat 300 mg; Lamivudin 300 mg; Efavirenz 600 mg.",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 450,
    "status": "LOW",
    "avgUsage": 45.0,
    "mos": 10.0,
    "expiryDate": "2027-10-31",
    "nomenklatur": "HIV / AIDS",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-022",
    "code": "PRG-022",
    "name": "Ampisilin inj 1000 mg/vial",
    "category": "Obat Program",
    "unit": "Vial",
    "quantity": 98,
    "status": "LOW",
    "avgUsage": 9.33,
    "mos": 10.5,
    "expiryDate": "2027-06-30",
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-023",
    "code": "PRG-023",
    "name": "Diazepam inj 5 mg/ml (Kesehatan Anak)",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 350,
    "status": "LOW",
    "avgUsage": 30.0,
    "mos": 11.67,
    "expiryDate": "2026-11-30",
    "nomenklatur": "Kesehatan Jiwa",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-024",
    "code": "PRG-024",
    "name": "Fenobarbital injeksi 50 mg/mL",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 150,
    "status": "LOW",
    "avgUsage": 17.5,
    "mos": 8.57,
    "expiryDate": "2027-09-19",
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-025",
    "code": "PRG-025",
    "name": "Fitomenadion (Vit. K1) injeksi 2 mg/mL",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 4630,
    "status": "AVAILABLE",
    "avgUsage": 192.5,
    "mos": 24.05,
    "expiryDate": "2027-04-30",
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-026",
    "code": "PRG-026",
    "name": "Gentamisin inj 40 mg/ml",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 123,
    "status": "LOW",
    "avgUsage": 14.75,
    "mos": 8.34,
    "expiryDate": "2027-10-30",
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-027",
    "code": "PRG-027",
    "name": "Kloramfenikol Salep Mata 1%",
    "category": "Obat Program",
    "unit": "Tube",
    "quantity": 2648,
    "status": "AVAILABLE",
    "avgUsage": 89.0,
    "mos": 29.75,
    "expiryDate": "2027-07-30",
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-028",
    "code": "PRG-028",
    "name": "Kloramfenikol Tetes Mata 1%",
    "category": "Obat Program",
    "unit": "Botol",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-029",
    "code": "PRG-029",
    "name": "Levo Tiroksin tab 50 mcg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-030",
    "code": "PRG-030",
    "name": "Oksitetrasiklin Salep Mata 1%",
    "category": "Obat Program",
    "unit": "Tube",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-031",
    "code": "PRG-031",
    "name": "Kalsium Glukonat inj 10%",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 184,
    "status": "LOW",
    "avgUsage": 24.5,
    "mos": 7.51,
    "expiryDate": "2026-11-30",
    "nomenklatur": "Kesehatan Ibu & Anak",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-032",
    "code": "PRG-032",
    "name": "Magnesium sulfat inj 20%",
    "category": "Obat Program",
    "unit": "Botol/Kofl",
    "quantity": 153,
    "status": "LOW",
    "avgUsage": 18.08,
    "mos": 8.46,
    "expiryDate": "2026-12-30",
    "nomenklatur": "Kesehatan Ibu & Anak",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-033",
    "code": "PRG-033",
    "name": "Magnesium Sulfat inj 40%",
    "category": "Obat Program",
    "unit": "Botol/Kofl",
    "quantity": 386,
    "status": "LOW",
    "avgUsage": 31.25,
    "mos": 12.35,
    "expiryDate": "2027-03-11",
    "nomenklatur": "Kesehatan Ibu & Anak",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-034",
    "code": "PRG-034",
    "name": "Metil Ergometrin Maleat inj 0,20 mg/ml",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 365,
    "status": "LOW",
    "avgUsage": 108.75,
    "mos": 3.36,
    "expiryDate": "2027-06-30",
    "nomenklatur": "Kesehatan Ibu & Anak",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-035",
    "code": "PRG-035",
    "name": "Metronidazol infus 5 mg/ml",
    "category": "Obat Program",
    "unit": "Botol/Kofl",
    "quantity": 660,
    "status": "AVAILABLE",
    "avgUsage": 5.42,
    "mos": 121.85,
    "expiryDate": "2031-02-28",
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-036",
    "code": "PRG-036",
    "name": "Oksitosin inj 10 IU/ml",
    "category": "Obat Program",
    "unit": "Vial",
    "quantity": 675,
    "status": "AVAILABLE",
    "avgUsage": 223.33,
    "mos": 3.02,
    "expiryDate": "2028-06-30",
    "nomenklatur": "Kesehatan Ibu & Anak",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-037",
    "code": "PRG-037",
    "name": "Amitriptilin tab 25 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 14900,
    "status": "AVAILABLE",
    "avgUsage": 566.67,
    "mos": 26.29,
    "expiryDate": "2027-01-30",
    "nomenklatur": "Kesehatan Jiwa",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-038",
    "code": "PRG-038",
    "name": "Diazepam inj 5 mg/ml",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 490,
    "status": "LOW",
    "avgUsage": 60.83,
    "mos": 8.05,
    "expiryDate": "2027-12-31",
    "nomenklatur": "Kesehatan Jiwa",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-039",
    "code": "PRG-039",
    "name": "Diazepam tab 5 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 1400,
    "status": "AVAILABLE",
    "avgUsage": 66.67,
    "mos": 21.0,
    "expiryDate": "2028-01-31",
    "nomenklatur": "Kesehatan Jiwa",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-040",
    "code": "PRG-040",
    "name": "Flufenazine Dekanoat inj 25 mg/ml",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 30,
    "status": "LOW",
    "avgUsage": 14.17,
    "mos": 2.12,
    "expiryDate": "2026-07-31",
    "nomenklatur": "Tuberkulosis (TBC)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-041",
    "code": "PRG-041",
    "name": "Haloperidol Dekanoat inj 50 mg/ml",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 15,
    "status": "LOW",
    "avgUsage": 0.0,
    "mos": null,
    "expiryDate": "2027-11-09",
    "nomenklatur": "Tuberkulosis (TBC)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-042",
    "code": "PRG-042",
    "name": "Haloperidol injeksi 5 mg/ml",
    "category": "Obat Program",
    "unit": "Ampul",
    "quantity": 2,
    "status": "LOW",
    "avgUsage": 2.42,
    "mos": 0.83,
    "expiryDate": "2026-09-30",
    "nomenklatur": "Kesehatan Jiwa",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-043",
    "code": "PRG-043",
    "name": "Haloperidol Tablet 5 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 11000,
    "status": "AVAILABLE",
    "avgUsage": 1300.0,
    "mos": 8.46,
    "expiryDate": "2026-09-30",
    "nomenklatur": "Kesehatan Jiwa",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-044",
    "code": "PRG-044",
    "name": "Klorpromazin HCL tab 100 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 391.67,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-045",
    "code": "PRG-045",
    "name": "Risperidon tab 2 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 11750,
    "status": "AVAILABLE",
    "avgUsage": 462.5,
    "mos": 25.41,
    "expiryDate": "2026-07-30",
    "nomenklatur": "Kesehatan Jiwa",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-046",
    "code": "PRG-046",
    "name": "Trifluoperazine HCL tab 5 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 3400,
    "status": "AVAILABLE",
    "avgUsage": 66.67,
    "mos": 51.0,
    "expiryDate": "2027-02-28",
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-047",
    "code": "PRG-047",
    "name": "Triheksifenidil tab 2 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 22900,
    "status": "AVAILABLE",
    "avgUsage": 2041.67,
    "mos": 11.22,
    "expiryDate": "2028-11-30",
    "nomenklatur": "Kesehatan Jiwa",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-048",
    "code": "PRG-048",
    "name": "dapson tab 100 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Kusta (Lepra)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-049",
    "code": "PRG-049",
    "name": "klofazimin kaps dalam minyak 100 mg",
    "category": "Obat Program",
    "unit": "Kapsul",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Kusta (Lepra)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-050",
    "code": "PRG-050",
    "name": "MDT MB Anak",
    "category": "Obat Program",
    "unit": "paket",
    "quantity": 56,
    "status": "LOW",
    "avgUsage": 1.5,
    "mos": 37.33,
    "expiryDate": "2027-01-30",
    "nomenklatur": "Kusta (Lepra)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-051",
    "code": "PRG-051",
    "name": "MDT MB Dewasa",
    "category": "Obat Program",
    "unit": "paket",
    "quantity": 15,
    "status": "LOW",
    "avgUsage": 13.67,
    "mos": 1.1,
    "expiryDate": "2027-01-30",
    "nomenklatur": "Kusta (Lepra)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-052",
    "code": "PRG-052",
    "name": "MDT PB Anak",
    "category": "Obat Program",
    "unit": "paket",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Kusta (Lepra)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-053",
    "code": "PRG-053",
    "name": "MDT PB Dewasa",
    "category": "Obat Program",
    "unit": "paket",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Kusta (Lepra)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-054",
    "code": "PRG-054",
    "name": "Prednison 5 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 34600,
    "status": "AVAILABLE",
    "avgUsage": 1725.0,
    "mos": 20.06,
    "expiryDate": "2027-06-30",
    "nomenklatur": "Obat Program Prioritas",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-055",
    "code": "PRG-055",
    "name": "Rifampisin tab 300 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 0,
    "status": "EMPTY",
    "avgUsage": 0.0,
    "mos": 0.0,
    "expiryDate": null,
    "nomenklatur": "Kusta (Lepra)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-056",
    "code": "PRG-056",
    "name": "Rifampisin tab 450 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 200,
    "status": "LOW",
    "avgUsage": 0.0,
    "mos": null,
    "expiryDate": "2027-02-28",
    "nomenklatur": "Kusta (Lepra)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-057",
    "code": "PRG-057",
    "name": "Rifampisin tab 600 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 500,
    "status": "AVAILABLE",
    "avgUsage": 33.33,
    "mos": 15.0,
    "expiryDate": "2027-02-28",
    "nomenklatur": "Kusta (Lepra)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-058",
    "code": "PRG-058",
    "name": "DHP (Dehidro Artemisin + Piperaquin)",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 279,
    "status": "LOW",
    "avgUsage": 103.5,
    "mos": 2.7,
    "expiryDate": "2027-02-28",
    "nomenklatur": "Malaria",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-059",
    "code": "PRG-059",
    "name": "Primakuin tab 15 mg",
    "category": "Obat Program",
    "unit": "Tablet",
    "quantity": 6470,
    "status": "AVAILABLE",
    "avgUsage": 232.5,
    "mos": 27.83,
    "expiryDate": "2026-10-30",
    "nomenklatur": "Malaria",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-prg-060",
    "code": "PRG-060",
    "name": "OAT FDC Kat. 1",
    "category": "Obat Program",
    "unit": "Paket",
    "quantity": 219,
    "status": "LOW",
    "avgUsage": 90.67,
    "mos": 2.42,
    "expiryDate": "2028-03-31",
    "nomenklatur": "Tuberkulosis (TBC)",
    "source": "PROGRAM",
    "updatedAt": "2026-06-30"
  },
  {
    "id": "stk-150",
    "code": "OBE-001",
    "name": "Epinefrin (Adrenalin) Injeksi 1 mg/ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 350,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-151",
    "code": "OBE-002",
    "name": "Atropin Sulfat Injeksi 0.25 mg/ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 420,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-152",
    "code": "OBE-003",
    "name": "Lidokain Injeksi 2% 2 ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 1850,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-153",
    "code": "OBE-004",
    "name": "Dexamethasone Injeksi 5 mg/ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 2400,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-154",
    "code": "OBE-005",
    "name": "Diphenhydramine Injeksi 10 mg/ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 890,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-155",
    "code": "OBE-006",
    "name": "Furosemide Injeksi 10 mg/ml 2 ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 640,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-156",
    "code": "OBE-007",
    "name": "Diazepam Injeksi 5 mg/ml 2 ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 380,
    "status": "LOW",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-157",
    "code": "OBE-008",
    "name": "Diazepam Rektal Tube 5 mg",
    "category": "Obat Emergensi",
    "unit": "Tube",
    "quantity": 140,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-158",
    "code": "OBE-009",
    "name": "Diazepam Rektal Tube 10 mg",
    "category": "Obat Emergensi",
    "unit": "Tube",
    "quantity": 120,
    "status": "LOW",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-159",
    "code": "OBE-010",
    "name": "Oksitosin Injeksi 10 IU/ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 1950,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-160",
    "code": "OBE-011",
    "name": "Metilergometrin Injeksi 0.2 mg/ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 520,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-161",
    "code": "OBE-012",
    "name": "Magnesium Sulfat (MgSO4) 20% 25 ml",
    "category": "Obat Emergensi",
    "unit": "Vial",
    "quantity": 280,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-162",
    "code": "OBE-013",
    "name": "Magnesium Sulfat (MgSO4) 40% 25 ml",
    "category": "Obat Emergensi",
    "unit": "Vial",
    "quantity": 340,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-163",
    "code": "OBE-014",
    "name": "Kalsium Glukonat Injeksi 10% 10 ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 95,
    "status": "LOW",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-164",
    "code": "OBE-015",
    "name": "Naloxone Injeksi 0.4 mg/ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 40,
    "status": "EMPTY",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-165",
    "code": "OBE-016",
    "name": "Aminofilin Injeksi 24 mg/ml 10 ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 210,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-166",
    "code": "OBE-017",
    "name": "Asam Traneksamat Injeksi 100 mg/ml 5 ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 480,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-167",
    "code": "OBE-018",
    "name": "Fitomenadion (Vit K1) Injeksi 2 mg/ml",
    "category": "Obat Emergensi",
    "unit": "Ampul",
    "quantity": 850,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-168",
    "code": "OBE-019",
    "name": "Natrium Bikarbonat (Meylon) 8.4% 25 ml",
    "category": "Obat Emergensi",
    "unit": "Vial",
    "quantity": 60,
    "status": "EMPTY",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-169",
    "code": "OBE-020",
    "name": "Dextrose 40% Injeksi 25 ml",
    "category": "Obat Emergensi",
    "unit": "Flakon",
    "quantity": 320,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Obat Emergensi",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-170",
    "code": "VAK-001",
    "name": "Vaksin Hepatitis B Rekombinan (HB0)",
    "category": "Vaksin & Serum",
    "unit": "Uniject",
    "quantity": 1450,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-171",
    "code": "VAK-002",
    "name": "Vaksin BCG 0.05 mg",
    "category": "Vaksin & Serum",
    "unit": "Ampul",
    "quantity": 620,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-172",
    "code": "VAK-003",
    "name": "Pelarut Vaksin BCG",
    "category": "Vaksin & Serum",
    "unit": "Ampul",
    "quantity": 620,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-173",
    "code": "VAK-004",
    "name": "Vaksin Polio Tetes (bOPV)",
    "category": "Vaksin & Serum",
    "unit": "Vial",
    "quantity": 840,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-174",
    "code": "VAK-005",
    "name": "Vaksin Polio Suntik (IPV)",
    "category": "Vaksin & Serum",
    "unit": "Vial",
    "quantity": 530,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-175",
    "code": "VAK-006",
    "name": "Vaksin DPT-HB-Hib (Pentabio)",
    "category": "Vaksin & Serum",
    "unit": "Vial",
    "quantity": 1120,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-176",
    "code": "VAK-007",
    "name": "Vaksin Campak Rubella (MR)",
    "category": "Vaksin & Serum",
    "unit": "Vial",
    "quantity": 780,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-177",
    "code": "VAK-008",
    "name": "Pelarut Vaksin Campak Rubella (MR)",
    "category": "Vaksin & Serum",
    "unit": "Ampul",
    "quantity": 780,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-178",
    "code": "VAK-009",
    "name": "Vaksin Rotavirus",
    "category": "Vaksin & Serum",
    "unit": "Tube",
    "quantity": 490,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-179",
    "code": "VAK-010",
    "name": "Vaksin PCV (Pneumokokus Konyugasi)",
    "category": "Vaksin & Serum",
    "unit": "Vial",
    "quantity": 640,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-180",
    "code": "VAK-011",
    "name": "Vaksin HPV (Human Papillomavirus)",
    "category": "Vaksin & Serum",
    "unit": "Vial",
    "quantity": 310,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-181",
    "code": "VAK-012",
    "name": "Vaksin Tetanus Toksoid (Td)",
    "category": "Vaksin & Serum",
    "unit": "Vial",
    "quantity": 890,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-182",
    "code": "VAK-013",
    "name": "Vaksin Difteri Tetanus (DT)",
    "category": "Vaksin & Serum",
    "unit": "Vial",
    "quantity": 460,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-183",
    "code": "VAK-014",
    "name": "Serum Anti Bisa Ular (SABU) Polivalen",
    "category": "Vaksin & Serum",
    "unit": "Vial",
    "quantity": 18,
    "status": "EMPTY",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-184",
    "code": "VAK-015",
    "name": "Serum Anti Tetanus (ATS) 1500 IU",
    "category": "Vaksin & Serum",
    "unit": "Ampul",
    "quantity": 75,
    "status": "LOW",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "Vaksin & Serum",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-185",
    "code": "BMH-001",
    "name": "Spuit / Alat Suntik 1 ml",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 18500,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-186",
    "code": "BMH-002",
    "name": "Spuit / Alat Suntik 3 ml",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 24000,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-187",
    "code": "BMH-003",
    "name": "Spuit / Alat Suntik 5 ml",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 16000,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-188",
    "code": "BMH-004",
    "name": "Spuit / Alat Suntik 10 ml",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 7800,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-189",
    "code": "BMH-005",
    "name": "Spuit / Alat Suntik 20 ml",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 2400,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-190",
    "code": "BMH-006",
    "name": "Spuit / Alat Suntik 50 ml Catheter Tip",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 850,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-191",
    "code": "BMH-007",
    "name": "Infus Set Dewasa (Macro Dropper)",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 4200,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-192",
    "code": "BMH-008",
    "name": "Infus Set Anak (Micro Dropper)",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 2100,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-193",
    "code": "BMH-009",
    "name": "Abocath / IV Catheter No. 18",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 1950,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-194",
    "code": "BMH-010",
    "name": "Abocath / IV Catheter No. 20",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 3400,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-195",
    "code": "BMH-011",
    "name": "Abocath / IV Catheter No. 22",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 4100,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-196",
    "code": "BMH-012",
    "name": "Abocath / IV Catheter No. 24 (Pediatrik)",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 2800,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-197",
    "code": "BMH-013",
    "name": "Infus Cairan Ringer Laktat (RL) 500 ml",
    "category": "BMHP / Alkes",
    "unit": "Botol",
    "quantity": 4500,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-198",
    "code": "BMH-014",
    "name": "Infus Cairan NaCl 0.9% 500 ml",
    "category": "BMHP / Alkes",
    "unit": "Botol",
    "quantity": 5200,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-199",
    "code": "BMH-015",
    "name": "Infus Cairan Dextrose 5% 500 ml",
    "category": "BMHP / Alkes",
    "unit": "Botol",
    "quantity": 2800,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-200",
    "code": "BMH-016",
    "name": "Infus Cairan D5 1/4 NS 500 ml",
    "category": "BMHP / Alkes",
    "unit": "Botol",
    "quantity": 1400,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-201",
    "code": "BMH-017",
    "name": "Water for Injection (Pelarut) 25 ml",
    "category": "BMHP / Alkes",
    "unit": "Flakon",
    "quantity": 1800,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-202",
    "code": "BMH-018",
    "name": "Kasa Hidrofil Steril 16x16 cm",
    "category": "BMHP / Alkes",
    "unit": "Kotak",
    "quantity": 1200,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-203",
    "code": "BMH-019",
    "name": "Kasa Gulung Perban 4 meter x 5 cm",
    "category": "BMHP / Alkes",
    "unit": "Rol",
    "quantity": 3500,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-204",
    "code": "BMH-020",
    "name": "Kasa Gulung Perban 4 meter x 10 cm",
    "category": "BMHP / Alkes",
    "unit": "Rol",
    "quantity": 2900,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-205",
    "code": "BMH-021",
    "name": "Kapas Pembalut Medis 250 gram",
    "category": "BMHP / Alkes",
    "unit": "Rol",
    "quantity": 850,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-206",
    "code": "BMH-022",
    "name": "Plester Medis Roll Kain 5 yard x 2 inch",
    "category": "BMHP / Alkes",
    "unit": "Rol",
    "quantity": 620,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-207",
    "code": "BMH-023",
    "name": "Micropore / Plester Kertas 1 inch",
    "category": "BMHP / Alkes",
    "unit": "Rol",
    "quantity": 740,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-208",
    "code": "BMH-024",
    "name": "Povidone Iodine 10% Larutan 300 ml",
    "category": "BMHP / Alkes",
    "unit": "Botol",
    "quantity": 430,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-209",
    "code": "BMH-025",
    "name": "Alkohol 70% 1000 ml",
    "category": "BMHP / Alkes",
    "unit": "Botol",
    "quantity": 680,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-210",
    "code": "BMH-026",
    "name": "Sarung Tangan Medis Non-Steril Size M",
    "category": "BMHP / Alkes",
    "unit": "Kotak",
    "quantity": 1850,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-211",
    "code": "BMH-027",
    "name": "Sarung Tangan Medis Non-Steril Size L",
    "category": "BMHP / Alkes",
    "unit": "Kotak",
    "quantity": 1420,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-212",
    "code": "BMH-028",
    "name": "Sarung Tangan Steril No. 7.5",
    "category": "BMHP / Alkes",
    "unit": "Pasang",
    "quantity": 2100,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-213",
    "code": "BMH-029",
    "name": "Masker Bedah 3-Ply Earloop",
    "category": "BMHP / Alkes",
    "unit": "Kotak",
    "quantity": 2900,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-214",
    "code": "BMH-030",
    "name": "Urine Bag 2000 ml dengan T-Valve",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 820,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-215",
    "code": "BMH-031",
    "name": "Foley Catheter 2-Way No. 16",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 450,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-216",
    "code": "BMH-032",
    "name": "Foley Catheter 2-Way No. 18",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 380,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-217",
    "code": "BMH-033",
    "name": "Feeding Tube / NGT No. 16 Dewasa",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 290,
    "status": "LOW",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-218",
    "code": "BMH-034",
    "name": "Feeding Tube / NGT No. 8 Bayi/Anak",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 240,
    "status": "LOW",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-219",
    "code": "BMH-035",
    "name": "Benang Bedah Silk 3/0 dengan Jarum",
    "category": "BMHP / Alkes",
    "unit": "Sachet",
    "quantity": 950,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-220",
    "code": "BMH-036",
    "name": "Benang Bedah Chromic Catgut 3/0",
    "category": "BMHP / Alkes",
    "unit": "Sachet",
    "quantity": 880,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-221",
    "code": "BMH-037",
    "name": "Jarum Kulit / Surgical Needles",
    "category": "BMHP / Alkes",
    "unit": "Lusin",
    "quantity": 110,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-222",
    "code": "BMH-038",
    "name": "Bilah Pisau Bedah (Scalpel Blade) No. 11",
    "category": "BMHP / Alkes",
    "unit": "Kotak",
    "quantity": 140,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-223",
    "code": "BMH-039",
    "name": "Safety Box Pengolah Limbah Jarum 5L",
    "category": "BMHP / Alkes",
    "unit": "Pcs",
    "quantity": 320,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  },
  {
    "id": "stk-224",
    "code": "BMH-040",
    "name": "Kantong Plastik Kuning Limbah Medis",
    "category": "BMHP / Alkes",
    "unit": "Pak",
    "quantity": 210,
    "status": "AVAILABLE",
    "avgUsage": 0,
    "mos": null,
    "expiryDate": null,
    "nomenklatur": "BMHP / Alkes",
    "source": "MANUAL",
    "updatedAt": "2026-08-31"
  }
];
